# Generated by Django 2.2.12 on 2022-05-24 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=36)),
                ('date', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('taxpayer_id', models.CharField(max_length=14)),
                ('uuid_status', models.CharField(max_length=3)),
                ('cod_status', models.CharField(max_length=3)),
                ('type', models.CharField(choices=[('F', 'Free'), ('W', 'WebService')], default='F', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36, unique=True)),
                ('date', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('S', 'Signed'), ('F', 'Finished'), ('C', 'Cancelled'), ('E', 'Error'), ('R', 'Rejected')], default='S', max_length=1)),
                ('type', models.CharField(choices=[('F', 'Free'), ('W', 'WebService')], default='F', max_length=1)),
                ('taxpayer_id', models.CharField(max_length=14)),
                ('rtaxpayer_id', models.CharField(max_length=14)),
                ('total', models.FloatField(default=0.0)),
                ('complement', models.CharField(max_length=50)),
                ('xml', models.FileField(blank=True, null=True, upload_to='cfdi/%Y/%m/%d')),
                ('version', models.CharField(default='3.3', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxpayer_id', models.CharField(max_length=14, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=256, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('U', 'Used'), ('C', 'Confirmed')], default='A', max_length=1)),
                ('uuid', models.CharField(db_index=True, max_length=36)),
            ],
            options={
                'unique_together': {('taxpayer_id', 'code')},
            },
        ),
    ]
