# Generated by Django 2.2.12 on 2022-05-24 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('A', 'Admin'), ('B', 'Billing'), ('C', 'Client'), ('G', 'Government'), ('S', 'Support')], default='C', max_length=1)),
                ('group', multiselectfield.db.fields.MultiSelectField(choices=[('AD', 'Admin'), ('BI', 'Billing'), ('CA', 'Cancelación'), ('CL', 'Client'), ('SA', 'Sat'), ('LO', 'Logs'), ('SU', 'Support'), ('US', 'Usuarios')], max_length=24)),
                ('status', models.CharField(choices=[('A', 'Active'), ('L', 'Locked'), ('T', 'Attempt Blocking'), ('D', 'Pending Deactivation'), ('R', 'Delete')], default='A', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
