# Generated by Django 2.2.12 on 2022-05-24 15:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=2)),
                ('descripcion', models.CharField(blank=True, max_length=55)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_gceh_actividad',
            },
        ),
        migrations.CreateModel(
            name='Aduana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=4)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_catalogos_aduana',
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=3, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_nomina_banco',
            },
        ),
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxpayer_id', models.CharField(max_length=14)),
                ('cod_status', models.CharField(max_length=255, null=True)),
                ('date', models.DateTimeField()),
                ('uuid', models.CharField(db_index=True, max_length=36)),
                ('uuid_status', models.CharField(max_length=36)),
                ('faultcode', models.CharField(max_length=255, null=True)),
                ('faultstring', models.CharField(max_length=255, null=True)),
                ('xml', models.FileField(blank=True, null=True, upload_to='cancelacion/%Y/%m/%d')),
                ('status', models.CharField(choices=[('E', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected'), ('D', 'Due'), ('C', 'Cancelled')], default='E', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=2)),
                ('descripcion', models.CharField(blank=True, max_length=50)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_obrasarte_caracteristica',
            },
        ),
        migrations.CreateModel(
            name='ClaveProdServ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('iva_trasladado', models.CharField(blank=True, default='Sí', max_length=50, null=True)),
                ('ieps_trasladado', models.CharField(blank=True, default='Opcional', max_length=50, null=True)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
                ('frontera', models.CharField(blank=True, default='0', max_length=1, null=True)),
                ('palabras_similares', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_catalogos_claveprodserv',
            },
        ),
        migrations.CreateModel(
            name='ClaveUnidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=3)),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
                ('simbolo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'sat_catalogos_claveunidad',
            },
        ),
        migrations.CreateModel(
            name='CodigoPostal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=10)),
                ('estado', models.CharField(blank=True, max_length=3, null=True)),
                ('municipio', models.CharField(blank=True, max_length=3, null=True)),
                ('localidad', models.CharField(blank=True, max_length=3, null=True)),
                ('frontera', models.CharField(default='0', max_length=1)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
                ('descripcion_hh', models.CharField(blank=True, max_length=70, null=True, verbose_name='Descripción del Huso Horario')),
                ('mes_inicio_hv', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mes Inicio Horario Verano')),
                ('dia_inicio_hv', models.CharField(blank=True, max_length=20, null=True, verbose_name='Día Inicio Horario Verano')),
                ('hora_inicio_hv', models.CharField(blank=True, max_length=10, null=True, verbose_name='Hora Horario Verano')),
                ('diferencia_hv', models.IntegerField(blank=True, null=True, verbose_name='Diferencia Horaria Verano')),
                ('mes_inicio_hi', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mes Inicio Horario Invierno')),
                ('dia_inicio_hi', models.CharField(blank=True, max_length=20, null=True, verbose_name='Día Inicio Horario Invierno')),
                ('hora_inicio_hi', models.CharField(blank=True, max_length=10, null=True, verbose_name='Hora Horario Invierno')),
                ('diferencia_hi', models.IntegerField(blank=True, null=True, verbose_name='Diferencia Horaria Invierno')),
            ],
            options={
                'db_table': 'sat_catalogos_codigopostal',
            },
        ),
        migrations.CreateModel(
            name='Colonia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=12)),
                ('cp', models.CharField(max_length=15)),
                ('descripcion', models.CharField(blank=True, max_length=450, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_cce_colonia',
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=3, unique=True)),
                ('pais', models.CharField(max_length=3)),
                ('descripcion', models.CharField(blank=True, max_length=55)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_ine_entidad',
            },
        ),
        migrations.CreateModel(
            name='EntidadFederativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=2)),
                ('descripcion', models.CharField(blank=True, max_length=55)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_notariospublicos_entidadfederativa',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=9)),
                ('pais', models.CharField(db_index=True, max_length=9)),
                ('descripcion', models.CharField(blank=True, max_length=450, null=True)),
            ],
            options={
                'db_table': 'sat_catalogos_estado',
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=3)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('bancarizado', models.CharField(blank=True, max_length=250, null=True)),
                ('numero_operacion', models.CharField(blank=True, max_length=250, null=True)),
                ('rfc_ordenante', models.CharField(blank=True, max_length=250, null=True)),
                ('cuenta_ordenante', models.CharField(blank=True, max_length=250, null=True)),
                ('patron_ordenante', models.CharField(blank=True, max_length=250, null=True)),
                ('rfc_beneficiario', models.CharField(blank=True, max_length=250, null=True)),
                ('cuenta_beneficiario', models.CharField(blank=True, max_length=250, null=True)),
                ('patron_beneficiaria', models.CharField(blank=True, max_length=250, null=True)),
                ('cadenapago', models.CharField(blank=True, max_length=250, null=True)),
                ('nombrebancoemisor', models.CharField(blank=True, max_length=250, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_catalogos_formapago',
            },
        ),
        migrations.CreateModel(
            name='FraccionArancelaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=24, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=700, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
                ('unidad', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'sat_cce_fraccionarancelaria',
            },
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=3)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('retencion', models.CharField(blank=True, max_length=5, null=True)),
                ('traslado', models.CharField(blank=True, max_length=5, null=True)),
                ('local_federal', models.CharField(blank=True, max_length=50, null=True)),
                ('entidad', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'sat_catalogos_impuesto',
            },
        ),
        migrations.CreateModel(
            name='Incoterm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=9)),
                ('descripcion', models.CharField(blank=True, max_length=450, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_cce_incoterm',
            },
        ),
        migrations.CreateModel(
            name='LCO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(db_index=True, max_length=13)),
                ('validez', models.CharField(max_length=1)),
                ('estatus', models.CharField(max_length=1)),
                ('serial', models.CharField(max_length=20)),
                ('inicio', models.CharField(max_length=19)),
                ('fin', models.CharField(max_length=19)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=6)),
                ('estado', models.CharField(max_length=9)),
                ('descripcion', models.CharField(blank=True, max_length=450, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_cce_localidad',
            },
        ),
        migrations.CreateModel(
            name='LRFC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(db_index=True, max_length=13)),
                ('sncf', models.BooleanField(default=False)),
                ('subcontratacion', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=30)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_catalogos_mes',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=3)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_catalogos_metodopago',
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=9)),
                ('descripcion', models.CharField(blank=True, max_length=450, null=True)),
                ('decimales', models.IntegerField(blank=True, null=True)),
                ('variacion', models.CharField(blank=True, max_length=50, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
                ('tipo_cambio', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'sat_catalogos_moneda',
            },
        ),
        migrations.CreateModel(
            name='MotivoTraslado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=9)),
                ('descripcion', models.CharField(blank=True, max_length=450, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_cce_motivotraslado',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=9)),
                ('estado', models.CharField(max_length=9)),
                ('descripcion', models.CharField(blank=True, max_length=450, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_cce_municipio',
            },
        ),
        migrations.CreateModel(
            name='NumeroPedimentoAduana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=2)),
                ('patente', models.CharField(blank=True, max_length=50, null=True)),
                ('ejercicio', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.CharField(blank=True, max_length=50, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_catalogos_numeropedimentoaduana',
            },
        ),
        migrations.CreateModel(
            name='OrigenRecurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=3, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=55, null=True)),
            ],
            options={
                'db_table': 'sat_nomina_origenrecurso',
            },
        ),
        migrations.CreateModel(
            name='PagoPedimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=4)),
                ('descripcion', models.CharField(max_length=150)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_gceh_pagopedimento',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=9)),
                ('descripcion', models.CharField(blank=True, max_length=450, null=True)),
                ('formato_codigopostal', models.CharField(blank=True, max_length=450, null=True)),
                ('rit', models.CharField(blank=True, max_length=450, null=True)),
                ('validacion_rit', models.CharField(blank=True, max_length=450, null=True)),
                ('agrupaciones', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'sat_catalogos_pais',
            },
        ),
        migrations.CreateModel(
            name='PatenteAduanal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=6)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_catalogos_patenteaduanal',
            },
        ),
        migrations.CreateModel(
            name='Pedimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=9)),
                ('descripcion', models.CharField(blank=True, max_length=450, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_catalogos_pedimento',
            },
        ),
        migrations.CreateModel(
            name='PeriodicidadPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=3, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=55, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_nomina_periodicidadpago',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=36)),
                ('cod_status', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('incidents', models.TextField(default='')),
                ('xml', models.FileField(blank=True, null=True, upload_to='recepcion/%Y/%m/%d')),
                ('taxpayer_id', models.CharField(max_length=14, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegimenFiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=4)),
                ('descripcion', models.CharField(max_length=255)),
                ('fisica', models.CharField(blank=True, max_length=4, null=True)),
                ('moral', models.CharField(blank=True, max_length=4, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_catalogos_regimenfiscal',
            },
        ),
        migrations.CreateModel(
            name='RiesgoPuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=3, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=55, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_nomina_riesgopuesto',
            },
        ),
        migrations.CreateModel(
            name='ServiceLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('initial', models.PositiveIntegerField(null=True)),
                ('final', models.PositiveIntegerField(null=True)),
                ('rejected', models.PositiveIntegerField(default=0)),
                ('incidents', models.PositiveIntegerField(default=0)),
                ('extemporaneous', models.PositiveIntegerField(default=0)),
                ('satisfied', models.PositiveIntegerField(default=0)),
                ('duplicated', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=3)),
                ('actividad', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=55)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_gceh_subactividad',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=4)),
                ('subactividad', models.CharField(max_length=3)),
                ('actividad', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=200)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_gceh_tarea',
            },
        ),
        migrations.CreateModel(
            name='TasaOCuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango', models.CharField(blank=True, max_length=255, null=True)),
                ('minimo', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('maximo', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('impuesto', models.CharField(blank=True, max_length=40, null=True)),
                ('factor', models.CharField(blank=True, max_length=20, null=True)),
                ('traslado', models.CharField(blank=True, max_length=20, null=True)),
                ('retencion', models.CharField(blank=True, max_length=20, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_catalogos_tasaocuota',
            },
        ),
        migrations.CreateModel(
            name='TipoBien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=2)),
                ('descripcion', models.CharField(blank=True, max_length=50)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_obrasarte_tipobien',
            },
        ),
        migrations.CreateModel(
            name='TipoCadenaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=3)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCombustible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=3)),
                ('descripcion', models.CharField(blank=True, max_length=55)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_ecc_tipocombustible',
            },
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=3)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sat_nomina_tipocontrato',
            },
        ),
        migrations.CreateModel(
            name='TipoDeComprobante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=3)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('maximo', models.CharField(blank=True, max_length=50, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_catalogos_tipodecomprobante',
            },
        ),
        migrations.CreateModel(
            name='TipoDecreto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=2)),
                ('descripcion', models.CharField(blank=True, max_length=150)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_renovsustitvehic_tipodecreto',
            },
        ),
        migrations.CreateModel(
            name='TipoDeduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=3, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_nomina_tipodeduccion',
            },
        ),
        migrations.CreateModel(
            name='TipoFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=20)),
            ],
            options={
                'db_table': 'sat_catalogos_tipofactor',
            },
        ),
        migrations.CreateModel(
            name='TipoHoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=3)),
                ('descripcion', models.CharField(blank=True, max_length=55, null=True)),
            ],
            options={
                'db_table': 'sat_nomina_tipohoras',
            },
        ),
        migrations.CreateModel(
            name='TipoIncapacidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=3, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'sat_nomina_tipoincapacidad',
            },
        ),
        migrations.CreateModel(
            name='TipoInmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=2)),
                ('descripcion', models.CharField(blank=True, max_length=55)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_notariospublicos_tipoinmueble',
            },
        ),
        migrations.CreateModel(
            name='TipoJornada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=3, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=55, null=True)),
            ],
            options={
                'db_table': 'sat_nomina_tipojornada',
            },
        ),
        migrations.CreateModel(
            name='TipoNomina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=3)),
                ('descripcion', models.CharField(blank=True, max_length=55, null=True)),
            ],
            options={
                'db_table': 'sat_nomina_tiponomina',
            },
        ),
        migrations.CreateModel(
            name='TipoOperacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=9, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=450, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_cce_tipooperacion',
            },
        ),
        migrations.CreateModel(
            name='TipoOtroPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=3, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_nomina_tipootropago',
            },
        ),
        migrations.CreateModel(
            name='TipoPercepcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=3, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_nomina_tipopercepcion',
            },
        ),
        migrations.CreateModel(
            name='TipoRegimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=3, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_nomina_tiporegimen',
            },
        ),
        migrations.CreateModel(
            name='TipoRelacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=3)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_catalogos_tiporelacion',
            },
        ),
        migrations.CreateModel(
            name='TipoSerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=7)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_certificadodestruccion_tiposerie',
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculoR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=2)),
                ('descripcion', models.CharField(blank=True, max_length=150)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_renovsustitvehic_tipovehiculor',
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculoS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=2)),
                ('descripcion', models.CharField(blank=True, max_length=150)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_renovsustitvehic_tipovehiculos',
            },
        ),
        migrations.CreateModel(
            name='TituloAdquirido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=2)),
                ('descripcion', models.CharField(blank=True, max_length=50)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_obrasarte_tituloadquirido',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=450, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_cce_unidadmedida',
            },
        ),
        migrations.CreateModel(
            name='UsoCFDI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=3)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fisica', models.CharField(blank=True, max_length=10, null=True)),
                ('moral', models.CharField(blank=True, max_length=10, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_catalogos_usocfdi',
            },
        ),
        migrations.CreateModel(
            name='VehiculoEnajenado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=2)),
                ('descripcion', models.CharField(blank=True, max_length=55)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sat_renovsustitvehic_vehiculoenajenado',
            },
        ),
        migrations.CreateModel(
            name='ServiceLevelDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('R', 'Rejected'), ('E', 'Extemporaneous'), ('I', 'Incidents')], default='R', max_length=1)),
                ('uuid', models.CharField(db_index=True, max_length=36)),
                ('taxpayer_id', models.CharField(max_length=14, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('incidents', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('detail', models.TextField(null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sat.ServiceLevel')),
            ],
        ),
    ]
