# Generated by Django 2.2.12 on 2022-05-24 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingCancellation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('taxpayer_id', models.CharField(max_length=14, null=True)),
                ('rtaxpayer_id', models.CharField(max_length=14, null=True)),
                ('invoice_type', models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso'), ('T', 'Traslado'), ('N', 'Nomina'), ('P', 'Pago')], default='I', max_length=1, null=True)),
                ('total', models.FloatField(default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('rtaxpayer_id', models.CharField(max_length=14)),
                ('response', models.CharField(choices=[('A', 'Aceptación'), ('R', 'Rechazo'), ('U', 'Desconocida')], default='A', max_length=1)),
                ('status', models.CharField(choices=[('1000', 'Se recibió la respuesta de la petición de forma exitosa'), ('1001', 'No existen peticiones de cancelación en espera de respuesta para el uuid'), ('1002', 'Ya se recibió una respuesta para la petición de cancelación del uuid'), ('1003', 'Sello No Corresponde al RFC Receptor'), ('1004', 'Existen más de una petición de cancelación para el mismo uuid'), ('1005', 'El uuid es nulo no posee el formato correcto'), ('1006', 'Se rebaso el número máximo de solicitudes permitidas'), ('996', 'Solicitud rechazada'), ('997', 'Plazo vencido'), ('998', 'Aceptación o Rechazo no realizado en el super portal'), ('999', 'Ocurrio un error durante el proceso de aceptacion rechazo')], default='1000', max_length=10)),
                ('notes', models.TextField(null=True)),
                ('last', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36)),
                ('date', models.DateTimeField(null=True)),
                ('total', models.FloatField(default=0.0)),
                ('invoice_type', models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso'), ('T', 'Traslado'), ('N', 'Nomina'), ('P', 'Pago')], default='I', max_length=1)),
                ('taxpayer_id', models.CharField(max_length=14)),
                ('rtaxpayer_id', models.CharField(max_length=14)),
                ('status', models.CharField(choices=[('W', 'Cancelado sin aceptación'), ('C', 'Cancelado con aceptación'), ('E', 'En proceso'), ('D', 'Plazo vencido'), ('U', 'Desconocido')], default='W', max_length=1)),
                ('status_sat', models.CharField(choices=[('V', 'Vigente'), ('C', 'Cancelado')], default='V', max_length=1)),
                ('notes', models.TextField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['uuid'], name='cancel_requ_uuid_17c1f4_idx'),
        ),
        migrations.AlterIndexTogether(
            name='request',
            index_together={('rtaxpayer_id', 'date')},
        ),
        migrations.AddIndex(
            model_name='cancellation',
            index=models.Index(fields=['uuid'], name='cancel_canc_uuid_6193bf_idx'),
        ),
        migrations.AlterIndexTogether(
            name='cancellation',
            index_together={('taxpayer_id', 'date')},
        ),
    ]
