from django.core.management.base import BaseCommand, CommandError
from django.conf import settings

from helpdesk.models import EmailTemplate
from pdb import set_trace

import fnmatch
class Command(BaseCommand):
  help = 'Command for update email templates support'

  #def add_arguments(self, parser):
  #    parser.add_argument('poll_id', nargs='+', type=int)

  def handle(self, *args, **options):
    try:
      template = EmailTemplate.objects.get(id=83)
      template = EmailTemplate.objects.get(id=83)
      template.plain_text = '''Hola,\r\n\r\nEl Ticket {{ ticket.title }} (\"{{ ticket.title }}\"){% if ticket.assigned_to %}, asignado a {{ ticket.assigned_to }}{% endif %} ha sido cerrado.\r\n\r\nTicket ID: {{ ticket.ticket }}\r\nCola: {{ queue.title }}\r\nTítulo: {{ ticket.title }}\r\nCreado: {{ ticket.created|date:\"l N jS Y, \\a\\t P\" }}\r\nRemitente: {{ ticket.submitter_email|default:\"Desconocido\" }}\r\nPrioridad: {{ ticket.get_priority_display }}\r\nEstado: {{ ticket.get_status }}\r\nAsignado a: {{ ticket.get_assigned_to }}\r\nVer online: {{ ticket.staff_url }} (login requerido)\r\n\r\nLa descripción original es:\r\n\r\n{{ ticket.description }}\r\n\r\nLa solución dada fue:\r\n\r\n{{ resolution }}\r\n\r\n'''
      template.html = '''<p style=\"font-family: sans-serif; font-size: 1em;\">Hola,</p>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">El Ticket <i>{{ ticket.title }}</i> ('{{ ticket.title }}'){% if ticket.assigned_to %}, asignado a {{ ticket.get_assigned_to }}{% endif %} ha sido cerrado.</p>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">\r\n<b>Ticket ID</b>: {{ ticket.ticket }}<br>\r\n<b>Cola</b>: {{ queue.title }}<br>\r\n<b>Título</b>: {{ ticket.title }}<br>\r\n<b>Creado</b>: {{ ticket.created|date:\"l N jS Y, \\a\\t P\" }}<br>\r\n<b>Remitente</b>: {{ ticket.submitter_email|default:\"Desconocido\" }}<br>\r\n<b>Prioridad</b>: {{ ticket.get_priority_display }}<br>\r\n<b>Estado</b>: {{ ticket.get_status }}<br>\r\n<b>Asignado a</b>: {{ ticket.get_assigned_to }}<br>\r\n<b><a href='{{ ticket.staff_url }}'>Ver online</a></b> para actualizar este Ticket (login requerido)</p>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">La descripción original es:</p>\r\n\r\n<blockquote style=\"font-family: sans-serif; font-size: 1em;\">{{ ticket.description|linebreaksbr }}</blockquote>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">La solución dada fue:</p>\r\n\r\n<blockquote style=\"font-family: sans-serif; font-size: 1em;\">{{ resolution }}</blockquote>\r\n\r\n'''
      template.save()

      template = EmailTemplate.objects.get(id=84)
      template = EmailTemplate.objects.get(id=84)
      template.plain_text = '''Hola,\r\n\r\nEl siguiente Ticket asignado a usted ha sido cerrado.\r\n\r\nTicket ID: {{ ticket.ticket }}\r\nCola: {{ queue.title }}\r\nTítulo: {{ ticket.title }}\r\nCreado: {{ ticket.created|date:\"l N jS Y, \\a\\t P\" }}\r\nRemitente: {{ ticket.submitter_email|default:\"Desconocido\" }}\r\nPrioridad: {{ ticket.get_priority_display }}\r\nEstado: {{ ticket.get_status }}\r\nAsignado a: {{ ticket.get_assigned_to }}.\r\n\r\n'''
      template.html = '''<p style=\"font-family: sans-serif; font-size: 1em;\">Hola,</p>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">El siguiente Ticket asignado a usted ha sido cerrado.</p>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">\r\n<b>Ticket ID</b>: {{ ticket.ticket }}<br>\r\n<b>Cola</b>: {{ queue.title }}<br>\r\n<b>Título</b>: {{ ticket.title }}<br>\r\n<b>Creado</b>: {{ ticket.created|date:\"l N jS Y, \\a\\t P\" }}<br>\r\n<b>Remitente</b>: {{ ticket.submitter_email|default:\"Desconocido\" }}<br>\r\n<b>Prioridad</b>: {{ ticket.get_priority_display }}<br>\r\n<b>Estado</b>: {{ ticket.get_status }}<br>\r\n<b>Asignado a</b>: {{ ticket.get_assigned_to }}<br>\r\n<b><a href='{{ ticket.staff_url }}'>Ver online</a></b> para actualizar este Ticket (login requerido)</p>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">La descripción original es:</p>\r\n\r\n<blockquote style=\"font-family: sans-serif; font-size: 1em;\">{{ ticket.description|linebreaksbr }}</blockquote>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">La solución dada fue:</p>\r\n\r\n<blockquote style=\"font-family: sans-serif; font-size: 1em;\">{{ ticket.resolution }}</blockquote>'''
      template.save()

      template = EmailTemplate.objects.get(id=85)
      template = EmailTemplate.objects.get(id=85)
      template.plain_text = '''Hola,\r\n\r\nRecientemente usted envió el Ticket \"{{ ticket.title }}\". Este e-mail es para confirmar que el Ticket ha sido cerrado.\r\n\r\nSi cree que se requiere trabajo adicional, por favor déjanoslo saber respondiendo a este correo dejando el asunto intacto.\r\n\r\nLa solución dada fue:\r\n\r\n{{ ticket.resolution }}\r\n\r\n'''
      template.html = '''<p style=\"font-family: sans-serif; font-size: 1em;\">Hola,</p>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">Recientemente usted envió el Ticket <i>{{ ticket.title }}</i>. Este e-mail es para confirmar que el Ticket ha sido cerrado.</p>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">La solución dada es:</p>\r\n\r\n<blockquote style=\"font-family: sans-serif; font-size: 1em;\">{{ ticket.resolution }}</blockquote>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">Si cree que se requiere trabajo adicional, por favor déjanoslo saber respondiendo a este correo dejando el asunto intacto.</p>'''
      template.save()

      template = EmailTemplate.objects.get(id=87)
      template = EmailTemplate.objects.get(id=87)
      template.plain_text = '''Hola,\r\n\r\nRecientemente usted envió el Ticket \"{{ ticket.title }}\". Este e-mail es para informarle que su Ticket ha sido escalado ya que ha estado abierto por mas tiempo del esperado.\r\n\r\nSe revisará su Ticket para darle una solución tan pronto como sea posible.\r\n\r\n'''
      template.html = '''<p style=\"font-family: sans-serif; font-size: 11pt;\">Hola,</p>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 11pt;\">Recientemente usted envió el Ticket <i>{{ ticket.title }}</i>. Este e-mail es para informarle que su Ticket ha sido escalado ya que ha estado abierto por mas tiempo del esperado.</p>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 11pt;\">Se revisará su Ticket para darle una solución tan pronto como sea posible.</p>\r\n\r\n'''
      template.save()

      template = EmailTemplate.objects.get(id=90)
      template = EmailTemplate.objects.get(id=90)
      template.plain_text = '''Hola,\r\n\r\nEste e-mail es para informar que recibimos su consulta \"{{ ticket.title }}\". \r\n\r\nUsted no debe realizar nada en este momento. Su Ticket está identificado con el número {{ ticket.ticket }} y será respondido prontamente.\r\n\r\nSi desea enviar detalles adicionales, o si tiene cualquier consulta con respecto a este Ticket por favor incluya el Ticket ID '{{ ticket.ticket }}' en el asunto. La manera mas fácil de hacerlo es presionando el botón de \"respuesta\" a este mensaje.\r\n\r\nNosotros trabajaremos en su consulta y la resolveremos tan pronto como sea posible. Usted recibirá actualizaciones y la solución a su consulta a través de este e-mail.\r\n'''
      template.html = '''<p style=\"font-family: sans-serif; font-size: 1em;\">Hola,</p>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">Este e-mail es para informar que recibimos su consulta <i>{{ ticket.title }}</i>.</p>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">Usted no debe realizar nada en este momento. Su Ticket está identificado con el número <b>{{ ticket.ticket }}</b> y será respondido prontamente.</p>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">Si desea enviar detalles adicionales, o si tiene cualquier consulta con respecto a este Ticket por favor incluya el Ticket ID <b>{{ ticket.ticket }}</b> en el asunto. La manera mas fácil de hacerlo es presionando el botón de \"respuesta\" a este mensaje.</p>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">Nosotros trabajaremos en su consulta y la resolveremos tan pronto como sea posible. Usted recibirá actualizaciones y la solución a su consulta a través de este e-mail.</p>'''
      template.save()

      template = EmailTemplate.objects.get(id=91)
      template = EmailTemplate.objects.get(id=91)
      template.plain_text = '''Hola,\r\n\r\nEl siguiente Ticket ha sido resuelto:\r\n\r\nTicket ID: {{ ticket.ticket }}\r\nCola: {{ queue.title }}\r\nTítulo: {{ ticket.title }}\r\nCreado: {{ ticket.created|date:\"l N jS Y, \\a\\t P\" }}\r\nRemitente: {{ ticket.submitter_email|default:\"Desconocido\" }}\r\nPrioridad: {{ ticket.get_priority_display }}\r\nEstado: {{ ticket.get_status }}\r\nAsignado a: {{ ticket.get_assigned_to }}\r\nLa descripción original es:\r\n\r\n{{ ticket.description }}\r\n\r\nLa solución dada fue:\r\n\r\n{{ ticket.resolution }}\r\n\r\nEsta solucion ha sido enviada al remitente, quien realizará la verificación antes de que pueda cerrar el Ticket.\r\n\r\n'''
      template.html = '''<p style=\"font-family: sans-serif; font-size: 1em;\">Hola,</p>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">Un ticket asignado a usted ha sido resuelto.</p>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">\r\n<b>Ticket ID</b>: {{ ticket.ticket }}<br>\r\n<b>Cola</b>: {{ queue.title }}<br>\r\n<b>Título</b>: {{ ticket.title }}<br>\r\n<b>Creado</b>: {{ ticket.created|date:\"l N jS Y, \\a\\t P\" }}<br>\r\n<b>Remitente</b>: {{ ticket.submitter_email|default:\"Desconocido\" }}<br>\r\n<b>Prioridad</b>: {{ ticket.get_priority_display }}<br>\r\n<b>Estado</b>: {{ ticket.get_status }}<br>\r\n<b>Asignado a</b>: {{ ticket.get_assigned_to }}<br>\r\n<b>La descripción original es:</p>\r\n\r\n<blockquote style=\"font-family: sans-serif; font-size: 1em;\">{{ ticket.description|linebreaksbr }}</blockquote>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">La solución dada fue:</p>\r\n\r\n<blockquote style=\"font-family: sans-serif; font-size: 1em;\">{{ ticket.resolution }}</blockquote>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">Esta solucion ha sido enviada al remitente, quien realizará la verificación antes de que pueda cerrar el Ticket.</p>'''
      template.save()

      template = EmailTemplate.objects.get(id=92)
      template = EmailTemplate.objects.get(id=92)
      template.plain_text = '''Hola,\r\n\r\nUn ticket asignado a usted ha sido resuelto.\r\n\r\nTicket ID: {{ ticket.ticket }}\r\nCola: {{ queue.title }}\r\nTítulo: {{ ticket.title }}\r\nCreado: {{ ticket.created|date:\"l N jS Y, \\a\\t P\" }}\r\nRemitente: {{ ticket.submitter_email|default:\"Desconocido\" }}\r\nPrioridad: {{ ticket.get_priority_display }}\r\nEstado: {{ ticket.get_status }}\r\nAsignado a: {{ ticket.get_assigned_to }}\r\n\r\nLa descripción original es:\r\n\r\n{{ ticket.description }}\r\n\r\nLa solución dada fue:\r\n\r\n{{ ticket.resolution }}\r\n\r\nEsta solución ha sido enviada al remitente, quien realizará la verificación antes de que pueda cerrar el Ticket.\r\n\r\n'''
      template.html = '''<p style=\"font-family: sans-serif; font-size: 1em;\">Hola,</p>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">Un ticket asignado a usted ha sido resuelto.</p>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">\r\n<b>Ticket ID</b>: {{ ticket.ticket }}<br>\r\n<b>Cola</b>: {{ queue.title }}<br>\r\n<b>Título</b>: {{ ticket.title }}<br>\r\n<b>Creado</b>: {{ ticket.created|date:\"l N jS Y, \\a\\t P\" }}<br>\r\n<b>Remitente</b>: {{ ticket.submitter_email|default:\"Desconocido\" }}<br>\r\n<b>Prioridad</b>: {{ ticket.get_priority_display }}<br>\r\n<b>Estado</b>: {{ ticket.get_status }}<br>\r\n<b>Asignado a</b>: {{ ticket.get_assigned_to }}<br></p>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">La descripción original es:</p>\r\n\r\n<blockquote style=\"font-family: sans-serif; font-size: 1em;\">{{ ticket.description|linebreaksbr }}</blockquote>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">La solución dada fue:</p>\r\n\r\n<blockquote style=\"font-family: sans-serif; font-size: 1em;\">{{ ticket.resolution }}</blockquote>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">Esta solucion ha sido enviada al remitente, quien realizará la verificación antes de que pueda cerrar el Ticket.</p>'''
      template.save()

      template = EmailTemplate.objects.get(id=93)
      template = EmailTemplate.objects.get(id=93)
      template.plain_text = '''Hola,\r\n\r\nRecientemente usted envió el Ticket \"{{ ticket.title }}\". Este e-mail es para informar que su Ticket ha sido resuelto.\r\n\r\nLa siguiente solución fue dada a su Ticket {{ ticket.ticket }}:\r\n\r\n{{ resolution }}\r\n\r\n¿Puede confirmar que esta solución cumple con lo que necesita para cerrar este Ticket? Si tiene otras consultas, o cree que esta solución no es la adecuada, por favor responda este mensaje manteniendo el asunto intacto.\r\n\r\n'''
      template.html = '''<p style=\"font-family: sans-serif; font-size: 1em;\">Hola,</p>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">Recientemente usted envió el Ticket <i>{{ ticket.title }}</i>. Este e-mail es para informar que su Ticket ha sido resuelto.</p>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">La siguiente solución fue dada a su Ticket <b>{{ ticket.ticket }}</b>:</p>\r\n\r\n<blockquote style=\"font-family: sans-serif; font-size: 1em;\">{{ resolution }}</blockquote>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">¿Puede confirmar que esta solución cumple con lo que necesita para cerrar este Ticket? Si tiene otras consultas, o cree que esta solución no es la adecuada, por favor responda este mensaje manteniendo el asunto intacto.</p>'''
      template.save()


      template = EmailTemplate.objects.get(id=94)
      template = EmailTemplate.objects.get(id=94)
      template.plain_text = '''Hola,\r\n\r\nEste e-mail es para informar que el Ticket {{ ticket.ticket }} (\"{{ ticket.title }}\") por {{ ticket.submitter_email }} ha sido actualizado.\r\n\r\nTicket ID: {{ ticket.ticket }}\r\nCola: {{ queue.title }}\r\nTítulo: {{ ticket.title }}\r\nCreado: {{ ticket.created|date:\"l N jS Y, \\a\\t P\" }}\r\nRemitente: {{ ticket.submitter_email|default:\"Desconocido\" }}\r\nPrioridad: {{ ticket.get_priority_display }}\r\nEstado: {{ ticket.get_status }}\r\nAsignado a: {{ ticket.get_assigned_to }}\r\n\r\nDescripción:\r\n\r\n{{ ticket.description }}\r\n\r\nSe agregó el siguiente comentario:\r\n\r\n{{ comment }}\r\n\r\nEsta información {% if private %}no {% endif %} fue enviada al remitente.\r\n\r\n'''
      template.html = '''<p style=\"font-family: sans-serif; font-size: 1em;\">Hola,</p>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">Este e-mail es para informar que el Ticket {{ ticket.ticket }} (\"{{ ticket.title }}\") por {{ ticket.submitter_email }} ha sido actualizado.</p>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">\r\n<b>Ticket ID</b>: {{ ticket.ticket }}<br>\r\n<b>Cola</b>: {{ queue.title }}<br>\r\n<b>Título</b>: {{ ticket.title }}<br>\r\n<b>Creado</b>: {{ ticket.created|date:\"l N jS Y, \\a\\t P\" }}<br>\r\n<b>Remitente</b>: {{ ticket.submitter_email|default:\"Desconocido\" }}<br>\r\n<b>Prioridad</b>: {{ ticket.get_priority_display }}<br>\r\n<b>Estado</b>: {{ ticket.get_status }}<br>\r\n<b>Asignado a</b>: {{ ticket.get_assigned_to }}<br></p>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">La descripción original es:</p>\r\n\r\n<blockquote style=\"font-family: sans-serif; font-size: 1em;\">{{ ticket.description|linebreaksbr }}</blockquote>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">Se agregó el siguiente comentario:</p>\r\n\r\n<blockquote style=\"font-family: sans-serif; font-size: 1em;\">{{ comment }}</blockquote>\r\n\r\n<p style=\"font-family: Tahoma, Arial, sans-serif; font-size: 11pt;\">Esta información {% if private %}no {% endif %} fue enviada al remitente.</p>'''
      template.save()

      template = EmailTemplate.objects.get(id=95)
      template = EmailTemplate.objects.get(id=95)
      template.plain_text = '''Hola,\r\n\r\nRecientemente usted envió el Ticket \"{{ ticket.title }}\". Este correo es para informar que su Ticket ha sido actualizado.\r\n\r\nSe agregó el siguiente comentario al Ticket {{ ticket.ticket }}:\r\n\r\n{{ comment }}\r\n\r\nSi necesita agregar información adicional por favor responda a este mensaje manteniendo el asunto intacto.\r\n\r\n'''
      template.html = '''<p style=\"font-family: sans-serif; font-size: 1em;\">Hola,</p>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">Este e-mail es para informar que el Ticket {{ ticket.ticket }} (\"{{ ticket.title }}\") por {{ ticket.submitter_email }}, que le fue asignado, ha sido actualizado.</p>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">\r\n<b>Ticket ID</b>: {{ ticket.ticket }}<br>\r\n<b>Cola</b>: {{ queue.title }}<br>\r\n<b>Título</b>: {{ ticket.title }}<br>\r\n<b>Creado</b>: {{ ticket.created|date:\"l N jS Y, \\a\\t P\" }}<br>\r\n<b>Remitente</b>: {{ ticket.submitter_email|default:\"Desconocido\" }}<br>\r\n<b>Prioridad</b>: {{ ticket.get_priority_display }}<br>\r\n<b>Estado</b>: {{ ticket.get_status }}<br>\r\n<b>Asignado a</b>: {{ ticket.get_assigned_to }}<br></p>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">La descripción original es:</p>\r\n\r\n<blockquote style=\"font-family: sans-serif; font-size: 1em;\">{{ ticket.description|linebreaksbr }}</blockquote>\r\n\r\n<p style=\"font-family: sans-serif; font-size: 1em;\">Se agregó el siguiente comentario:</p>\r\n\r\n<blockquote style=\"font-family: sans-serif; font-size: 1em;\">{{ comment }}</blockquote>\r\n\r\n<p style=\"font-family: Tahoma, Arial, sans-serif; font-size: 11pt;\">Esta información {% if private %}no {% endif %} fue enviada al remitente.</p>'''
      template.save()

      template = EmailTemplate.objects.get(id=96)
      template.plain_text = '''Hola,\r\n\r\nRecientemente usted envió el Ticket "{{ ticket.title }}". Este correo es para informar que su Ticket ha sido actualizado.\r\n\r\nSe agregó el siguiente comentario al Ticket {{ ticket.ticket }}:\r\n\r\n{{ comment }}\r\n\r\n'''
      template.html = '''<p style="font-family: sans-serif; font-size: 1em;">Hola,</p>\r\n\r\n<p style="font-family: sans-serif; font-size: 1em;">Recientemente usted envió el Ticket <i>{{ ticket.title }}</i>. Este correo es para informar que su Ticket ha sido actualizado.</p>\r\n\r\n<p style="font-family: sans-serif; font-size: 1em;">Se agregó el siguiente comentario al Ticket <b>{{ ticket.ticket }}</b>:</p>\r\n\r\n<blockquote style="font-family: sans-serif; font-size: 1em;">{{ comment }}</blockquote>\r\n\r\n'''
      template.save()
      print("Update EmailTemplates Successfully")
    except Exception as e:
      print(f'Exception => {e}')
    
