# Generated by Django 2.2.12 on 2022-12-29 20:10

import app.core.models
import app.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.FileField(blank=True, max_length=200, null=True, storage=app.core.models.OverrideFileSystemStorage(location='/data/soriana/logo/'), upload_to=app.core.storage.logo_storage, verbose_name='Logo'),
        ),
    ]
